version: '3'

services:
###> doctrine/doctrine-bundle ###
  db:
    image: mariadb:10.4
    container_name: db_chatapp
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      #      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'chatapp'
      MYSQL_USER: 'symfony'
      MYSQL_PASSWORD: 'symfony'
    ports:
      - "3309:3306"
    networks:
      - dev
###< doctrine/doctrine-bundle ###

  www:
    build: docker # on build le dockerfile dans php/
    container_name: www_chatapp
    #    user: "1000:1000"
    #    user: ${CURRENT_UID}
    ports:
      - "8000:80"
    volumes:
      - ./docker/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - dev

networks:
  dev:

volumes:
  db-data:
